# .goreleaser.yml
project_name: digitized

before:
  hooks:
  - go mod download

builds:
- main: .cmd/vhs-converter/main.go
  id: vhs-converter
  binary: vhs-converter
  goarch:
  - amd64
  goos:
  - linux
  - windows
  env:
  - CGO_ENABLED=0

archives:
- builds:
  - vhs-converter
  format: binary
